swagger: "2.0"
info:
  version: "1.0.0"
  title: "Mentor-Student API"
host: "api.example.com"
basePath: "/v1"
schemes:
  - "https"
paths:
  /mentors:
    get:
      tags:
        - "Mentors"
      summary: "Get all mentors"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Mentor"
    
  /students:
    get:
      tags:
        - "Students"
      summary: "Get all students"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Student"
   
  /students/{id}:
    get:
      tags:
        - "Students"
      summary: "Get a student by ID"
      parameters:
        - in: "path"
          name: "id"
          description: "ID of the student to retrieve"
          required: true
          type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Student"
        404:
          description: "Student not found"
   
    delete:
      tags:
        - "Students"
      summary: "Delete a student"
      parameters:
        - in: "path"
          name: "id"
          description: "ID of the student to delete"
          required: true
          type: "integer"
      responses:
        204:
          description: "Student deleted successfully"
        404:
          description: "Student not found"
  /teams:
    get:
      tags:
        - "Teams"
      summary: "Get all teams"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Team"
    post:
      tags:
        - "Teams"
      summary: "Create a new team"
      parameters:
        - in: "body"
          name: "team"
          description: "Team object to be created"
          required: true
          schema:
            $ref: "#/definitions/Team"
      responses:
        201:
          description: "Team created successfully"
        400:
          description: "Invalid request"
  /teams/{id}:
    get:
      tags:
        - "Teams"
      summary: "Get a team by ID"
      parameters:
        - in: "path"
          name: "id"
          description: "ID of the team to retrieve"
          required: true
          type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Team"
        404:
          description: "Team not found"
    put:
      tags:
        - "Teams"
      summary: "Update a team"
      parameters:
        - in: "path"
          name: "id"
          description: "ID of the team to update"
          required: true
          type: "integer"
        - in: "body"
          name: "team"
          description: "Updated team object"
          required: true
          schema:
            $ref: "#/definitions/Team"
      responses:
        200:
          description: "Team updated successfully"
        400:
          description: "Invalid request"
        404:
          description: "Team not found"
   
  /sessions:
    get:
      tags:
        - "Sessions"
      summary: "Get all sessions"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Session"
    post:
      tags:
        - "Sessions"
      summary: "Create a new session"
      parameters:
        - in: "body"
          name: "session"
          description: "Session object to be created"
          required: true
          schema:
            $ref: "#/definitions/Session"
      responses:
        201:
          description: "Session created successfully"
        400:
          description: "Invalid request"
  /sessions/{id}:
    get:
      tags:
        - "Sessions"
      summary: "Get a session by ID"
      parameters:
        - in: "path"
          name: "id"
          description: "ID of the session to retrieve"
          required: true
          type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Session"
        404:
          description: "Session not found"
    put:
      tags:
        - "Sessions"
      summary: "Update a session"
      parameters:
        - in: "path"
          name: "id"
          description: "ID of the session to update"
          required: true
          type: "integer"
        - in: "body"
          name: "session"
          description: "Updated session object"
          required: true
          schema:
            $ref: "#/definitions/Session"
      responses:
        200:
          description: "Session updated successfully"
        400:
          description: "Invalid request"
        404:
          description: "Session not found"
    
  /attendance:
    get:
      tags:
        - "Attendance"
      summary: "Get all attendance records"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Attendance"
          
  /attendance/{id}:
    put:
      tags:
        - "Attendance"
      summary: "Update an attendance record"
      parameters:
        - in: "path"
          name: "id"
          description: "ID of the attendance record to update"
          required: true
          type: "integer"
        - in: "body"
          name: "attendance"
          description: "Updated attendance record object"
          required: true
          schema:
            $ref: "#/definitions/Attendance"
      responses:
        200:
          description: "Attendance record updated successfully"
        400:
          description: "Invalid request"
        404:
          description: "Attendance record not found"
          
  /attendance/student/{studentId}:
    get:
      tags:
        - "Attendance"
      summary: "Get attendance records by Student ID"
      parameters:
        - in: "path"
          name: "studentId"
          description: "ID of the student to retrieve attendance records for"
          required: true
          type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Attendance"
        404:
          description: "Student not found or no attendance records available"
          
    post:
      tags:
        - "Attendance"
      summary: "Mark attendance for a student in a session"
      parameters:
        - in: "path"
          name: "studentId"
          description: "ID of the student to mark attendance for"
          required: true
          type: "integer"
        - in: "body"
          name: "attendance"
          description: "Attendance object to be created"
          required: true
          schema:
            $ref: "#/definitions/Attendance"
      responses:
        201:
          description: "Attendance marked successfully"
        400:
          description: "Invalid request"


      
  /grades:
    get:
      tags:
        - "Grades"
      summary: "Get all grades"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Grade"

  /grades/{id}:
    put:
      tags:
        - "Grades"
      summary: "Update a grade"
      parameters:
        - in: "path"
          name: "id"
          description: "ID of the grade to update"
          required: true
          type: "integer"
        - in: "body"
          name: "grade"
          description: "Updated grade object"
          required: true
          schema:
            $ref: "#/definitions/Grade"
      responses:
        200:
          description: "Grade updated successfully"
        400:
          description: "Invalid request"
        404:
          description: "Grade not found"   
          
  /grades/student/{studentId}:
    get:
      tags:
        - "Grades"
      summary: "Get grades by Student ID"
      parameters:
        - in: "path"
          name: "studentId"
          description: "ID of the student to retrieve grades for"
          required: true
          type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Grade"
        404:
          description: "Student not found or no grades available"
          
    post:
      tags:
        - "Grades"
      summary: "Add a grade for a student in a session"
      parameters:
        - in: "path"
          name: "studentId"
          description: "ID of the student to add a grade for"
          required: true
          type: "integer"
        - in: "body"
          name: "grade"
          description: "Grade object to be created"
          required: true
          schema:
            $ref: "#/definitions/Grade"
      responses:
        201:
          description: "Grade added successfully"
        400:
          description: "Invalid request"

  /activities:
    get:
      tags:
        - "Activities"
      summary: "Get all activities"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Activity"

  

definitions:
  Mentor:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      email:
        type: "string"
  Student:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      email:
        type: "string"
      leader:
        type: "boolean"
      teamId:
        type: "integer"
  Team:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      leaderId:
        type: "integer"
  Session:
    type: "object"
    properties:
      id:
        type: "integer"
      date:
        type: "string"
        format: "date"
  Attendance:
    type: "object"
    properties:
      id:
        type: "integer"
      studentId:
        type: "integer"
      sessionId:
        type: "integer"
      present:
        type: "boolean"
  Grade:
    type: "object"
    properties:
      id:
        type: "integer"
      studentId:
        type: "integer"
      sessionId:
        type: "integer"
      grade:
        type: "integer"
      comment:
        type: "string"
  Activity:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
