CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     databaseVersion LONG,
                                     createDate TIMESTAMP,
                                     updateDate TIMESTAMP,
                                     name VARCHAR(50) NOT NULL,
                                     email VARCHAR(100) NOT NULL,
                                     role VARCHAR(100) NOT NULL,
                                     team_id INT
);

CREATE TABLE IF NOT EXISTS team (
                                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    databaseVersion LONG,
                                    createDate TIMESTAMP,
                                    updateDate TIMESTAMP,
                                    name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS activity (
                                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                        databaseVersion LONG,
                                        createDate TIMESTAMP,
                                        updateDate TIMESTAMP,
                                        name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS session (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                       databaseVersion LONG,
                                       createDate TIMESTAMP,
                                       updateDate TIMESTAMP,
                                       date VARCHAR(50) NOT NULL,
                                       activity_id INT
);

CREATE TABLE IF NOT EXISTS attendance (
                                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                          databaseVersion LONG,
                                          createDate TIMESTAMP,
                                          updateDate TIMESTAMP,
                                          student_id INT,
                                          session_id INT,
                                          present BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS grade (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     database_version LONG,
                                     create_date TIMESTAMP,
                                     update_date TIMESTAMP,
                                     student_id INT,
                                     session_id INT,
                                     grade INT NOT NULL,
                                     comment VARCHAR(500),
                                     mentor_id INT
);

CREATE TABLE IF NOT EXISTS team_activity (
                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                            database_version LONG,
                                            create_date TIMESTAMP,
                                            update_date TIMESTAMP,
                                            team_id INTEGER NOT NULL ,
                                            activity_id INTEGER NOT NULL ,
                                            FOREIGN KEY (team_id) REFERENCES team (id),
                                            FOREIGN KEY (activity_id) REFERENCES activity (id)
);

INSERT INTO team (name) VALUES ('Team A');
INSERT INTO team (name) VALUES ('Team B');
INSERT INTO team (name) VALUES ('Team C');
INSERT INTO team (name) VALUES ('Team D');

INSERT INTO users (name, email, role, team_id) VALUES ('John Doe', 'john.doe@example.com', 'leader', 1);
INSERT INTO users (name, email, role) VALUES ('Jane Smith', 'jane.smith@example.com', 'mentor');
INSERT INTO users (name, email, role, team_id) VALUES ('Emily Johnson', 'emily.johnson@example.com', 'student', 2);
INSERT INTO users (name, email, role) VALUES ('Michael Brown', 'michael.brown@example.com', 'student');
INSERT INTO users (name, email, role, team_id) VALUES ('Sophia Lee', 'sophia.lee@example.com', 'student', 1);

INSERT INTO activity (name) VALUES ('Activity 1');
INSERT INTO activity (name) VALUES ('Activity 2');
INSERT INTO activity (name) VALUES ('Activity 3');
INSERT INTO activity (name) VALUES ('Activity 4');

INSERT INTO session (date, activity_id) VALUES ('2023-07-18', 1);
INSERT INTO session (date, activity_id) VALUES ('2023-07-19', 2);
INSERT INTO session (date, activity_id) VALUES ('2023-07-20', 1);

INSERT INTO attendance (student_id, session_id, present) VALUES (2, 1, true);
INSERT INTO attendance (student_id, session_id, present) VALUES (1, 1, false);
INSERT INTO attendance (student_id, session_id, present) VALUES (3, 2, true);
INSERT INTO attendance (student_id, session_id, present) VALUES (2, 2, true);
INSERT INTO attendance (student_id, session_id, present) VALUES (1, 2, false);

INSERT INTO grade (student_id, session_id, grade, comment, mentor_id) VALUES (1, 1, 90, 'Good work!', 2);
INSERT INTO grade (student_id, session_id, grade, mentor_id) VALUES (2, 1, 85, 2);
INSERT INTO grade (student_id, session_id, grade, comment, mentor_id) VALUES (3, 1, 78, 'Work harder next time.', 2);
INSERT INTO grade (student_id, session_id, grade, comment, mentor_id) VALUES (3, 2, 92, 'Great improvement!', 2);
INSERT INTO grade (student_id, session_id, grade, mentor_id) VALUES (2, 2, 87, 2);

INSERT INTO team_activity (team_id, activity_id)
SELECT DISTINCT u.team_id, s.activity_id
FROM Attendance a
         JOIN Session s ON a.session_id = s.id
         JOIN Users u ON a.student_id = u.id
WHERE u.team_id IS NOT NULL AND s.activity_id IS NOT NULL;